/* tslint:disable */
/* eslint-disable */
/**
 * NotificationPortal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ChallengeStatus {
    Challenging = 'Challenging',
    Challenged = 'Challenged',
    Accepting = 'Accepting',
    Accepted = 'Accepted',
    Declining = 'Declining',
    Declined = 'Declined'
}

export function ChallengeStatusFromJSON(json: any): ChallengeStatus {
    return ChallengeStatusFromJSONTyped(json, false);
}

export function ChallengeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeStatus {
    return json as ChallengeStatus;
}

export function ChallengeStatusToJSON(value?: ChallengeStatus | null): any {
    return value as any;
}

