/* tslint:disable */
/* eslint-disable */
/**
 * NotificationPortal
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ChallengeStatus,
    ChallengeStatusFromJSON,
    ChallengeStatusFromJSONTyped,
    ChallengeStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface ChallengeModel
 */
export interface ChallengeModel {
    /**
     * 
     * @type {number}
     * @memberof ChallengeModel
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof ChallengeModel
     */
    readonly communityName: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeModel
     */
    readonly fromPlayer: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeModel
     */
    readonly toPlayer: string;
    /**
     * 
     * @type {ChallengeStatus}
     * @memberof ChallengeModel
     */
    status: ChallengeStatus;
    /**
     * 
     * @type {Date}
     * @memberof ChallengeModel
     */
    readonly date: Date;
}

export function ChallengeModelFromJSON(json: any): ChallengeModel {
    return ChallengeModelFromJSONTyped(json, false);
}

export function ChallengeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'communityName': json['communityName'],
        'fromPlayer': json['fromPlayer'],
        'toPlayer': json['toPlayer'],
        'status': ChallengeStatusFromJSON(json['status']),
        'date': (new Date(json['date'])),
    };
}

export function ChallengeModelToJSON(value?: ChallengeModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': ChallengeStatusToJSON(value.status),
    };
}


